import Head from 'next/head'
import { Inter } from 'next/font/google'
import Calculator from '../components/calculator'
import CalculatorPretty from '@/components/calculator-pretty'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      <button className="bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600 hover:from-blue-500 hover:via-blue-600 hover:to-blue-700 text-white font-bold py-2 px-4 rounded">
        Click me
      </button>

        <Calculator />
        <CalculatorPretty />
      </main>
    </>
  )
}
